name: 'Quickbase Action'
description: 'Deploy quickbase formulas and code pages'

inputs:
  realm-hostname:
    description: 'Realm Hostname'
    required: true
  app-id:
    description: 'Application ID'
    required: true

outputs:
  version:
    description: 'The version of the quickbase-cli tool'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.realm-hostname }}
    - ${{ inputs.app-id }}
